httpTimeout: 600000

nmHoistingLimits: none

nodeLinker: pnpm

packageExtensions:
  "@bull-board/api@*":
    peerDependencies:
      "@bull-board/ui": "*"
  "@tensorflow/tfjs@*":
    dependencies:
      long: "*"
  chartjs-adapter-date-fns@*:
    peerDependencies:
      date-fns: "*"
  consolidate@*:
    dependencies:
      ejs: "*"
  # these are needed to extend fastify types
  "@fastify/accepts@*":
    peerDependencies:
      fastify: "*"
  "@fastify/cookie@*":
    peerDependencies:
      fastify: "*"
  "@fastify/static@*":
    peerDependencies:
      fastify: "*"
  "@fastify/view@*":
    peerDependencies:
      fastify: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

progressBarStyle: patrick

yarnPath: .yarn/releases/yarn-3.3.0.cjs
